### ISSUE TITLE
Error: Broken text PPtr in file ... when opening the project

### ISSUE THREAD

**Issue by phantaaa** [TCKingCeryn/Multiplayer-Unity-FullBody-FPS-Controller#6]
Hello, firstly thank you so much for sharing this amazing asset, it's a source of inspiration for me to level up my game dev skills. However, when I tried opening the project in Unity, the console logger got spammed with errors like such:

`Broken text PPtr in file(Assets/PlanetMaenad/FullBodyFPSController/Art/Animations/Controllers/FullBodyControllerAnim.controller). Local file identifier (-4085322944760721974) doesn't exist!`

![console_errors](https://github.com/TCKingCeryn/Multiplayer-Unity-FullBody-FPS-Controller/assets/40706418/9c7e466b-8ca4-42c4-b151-0be2e64789d6)

Any idea what could be the issue? Am I missing some assets?
I'm using correct version of unity for the project: **2021.3.23f1**

**Comment by echeng8** [comment]
bump. i also have this issue. any fix?

**Comment by TCKingCeryn** [comment]
Ah that’s okay to ignore, it’s just an error with some of the naming of animator controllers. You can just clear those errors and continue, they’re not script errors, just editor nonsense hahaSent from my iPhoneOn Apr 13, 2024, at 9:38 PM, Evan Cheng ***@***.***> wrote:﻿
bump. i also have this issue. any fix?
